version: '3'
services:
  unifi-video-controller:
    build: .
    container_name: unifi-video-controller
    ports:
      - 1935:1935
      - 6666:6666
      - 7004:7004
      - 7080:7080
      - 7442:7442
      - 7443:7443
      - 7444:7444
      - 7445:7445
      - 7446:7446
      - 7447:7447
    volumes:
      - /atlas/unifi-video/data:/var/lib/unifi-video
      - /atlas/unifi-video/videos:/var/lib/unifi-video/videos
    tmpfs:
      - /var/cache/unifi-video
    environment:
      - TZ=America/Los_Angeles
      - DEBUG=1
      - CREATE_TMPFS=no
    cap_add:
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
